import { NgModule } from '@angular/core';
import { MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatToolbarModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatPaginatorModule,
  MatDialogModule,
  MatGridListModule,
  MatTabsModule,
  MatIconModule,
  MatStepperModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTableModule,
  MatSortModule,
  MatSnackBarModule,
  MatListModule,
  MatChipsModule,
  MatDividerModule,
  MatCheckboxModule,
  MatBadgeModule,
  MatMenuModule,
  MatSidenavModule
} from '@angular/material';

@NgModule({
  exports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatGridListModule,
    MatTabsModule,
    MatIconModule,
    MatStepperModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
    MatSortModule,
    MatSnackBarModule,
    MatListModule,
    MatChipsModule,
    MatDividerModule,
    MatCheckboxModule,
    MatBadgeModule,
    MatMenuModule,
    MatSidenavModule
  ]
})
export class AngularMaterialModule {}
